### ISSUE TITLE
Help with black wallet app

### ISSUE THREAD

**Issue by supertec2** [helium/wallet-app#542]
My phone is OPPO A16s and my app is v2.4.2(1700062404) when i go to web page for DAO hnt or Mobile or IOT it loads all ok but i cant connect my wallet like i used to it just comes up with error code;-10

Any ideas ???

**Comment by Kl1nt1nMOd** [comment]
@supertec2 Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID KP98T5 by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by Kl1nt1nMOd** [comment]
@supertec2 Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID KP98T5 by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by cokes518** [comment]
[Kl1nt1nMOd](https://github.com/Kl1nt1nMOd) is a scammer, please do not click on any links from them.

**Comment by ChewingGlass** [comment]
Out of curiosity, does this also happen on https://modular.heliumvote.com

**Comment by smaksimowicz** [comment]
hello, I couldn't find the moduler.heliumvote repo to report the problem. Namely, from the very beginning of the website's existence, I have had problems with opening the staking subpage. I get the error as in the picture.

`p24.js:26 Uncaught DOMException: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://connect.solflare.com" from accessing a cross-origin frame.
    at new P24ContentScript (chrome-extension://aiicmmpkicnndkhlnnloilpgncbpkbjj/src/assets/js/p24.js:26:29)
    at chrome-extension://aiicmmpkicnndkhlnnloilpgncbpkbjj/src/assets/js/p24.js:475:24`

![image](https://github.com/helium/wallet-app/assets/85828532/66dc5f02-496b-46d5-b953-50632c834aee)

**Comment by ChewingGlass** [comment]
It seems like you may be using some kind of blocking extension that stops solflare from loading. I'd recommend disabling that or trying in incognito mode.

**Comment by ChewingGlass** [comment]
Closing this issue due to inactivity.
